### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by jympetalmd** [csMACnz/coveralls.net#110] opened 2022-07-25 13:13 UTC
Using version 4.0.0 for .net6
Since a few days ago, we started receiving the 400 Error code from the upload process : 

docker run -v PATHTOCODE:/code --rm -i dotnet-coveralls:latest --opencover --useRelativePaths -i /code/reports/coverage.opencover.xml --repoToken **** --commitId XXXX --commitBranch XXX --commitAuthor Jenkins --commitEmail jenkins@org.com --jobId 485-6 --pullRequest 485

```
Using Git Data Provider 'Command line Arguments'
[2022-07-23T22:08:16.270Z] Failed to upload to coveralls
[2022-07-23T22:08:16.271Z] BadRequest - <html>
[2022-07-23T22:08:16.271Z] <head><title>400 Bad Request</title></head>
[2022-07-23T22:08:16.271Z] <body>
[2022-07-23T22:08:16.271Z] <center><h1>400 Bad Request</h1></center>
[2022-07-23T22:08:16.271Z] <hr><center>nginx</center>
[2022-07-23T22:08:16.271Z] </body>
[2022-07-23T22:08:16.271Z] </html>
```

I don't see any --debug flag so how is it possible to debug the problem ?

Thanks

**Comment by csMACnz** [comment] 2022-07-26 20:49
Hi there,
I haven't had a chance to look at this but have some initial thoughts.

Is New Relic APM installed on the machine this runs on? I've seen older versions cause corruption on http requests with .Net6

I see the error is coming back as an NGinx response. Do you have a proxy or reverse proxy on your network? It might be causing the issue interfering with the http traffic.

I don't think debug would help here as I can see the full "server" response and it doesn't give any detail other than the fact it is an NGinx error page.

Can you also verify if the previous major version of coveralls.net has the same issue? As the only difference is the dotnet upgrade.

**Comment by Giorgi** [comment] 2022-07-26 21:24
I have the same error on Appveyor as well as my local machine. I don't have NR installed on my machine.

**Comment by dejan-zdravkovski-snow** [comment] 2022-07-27 11:05
Hello @csMACnz ,
based on feedback from coveralls support, it's a networking issue related to NS resolution and migration to new server infrastructure.
Is it possible to actually implement the note related to hardcoded base uri 'https://coveralls.io' 
https://github.com/csMACnz/coveralls.net/blob/c6502f1409dafe29ddbad189d629cb5cf4b620af/src/csmacnz.Coveralls/Program.cs#L12
and make it configurable as input parameter?

**Comment by csMACnz** [comment] 2022-07-27 11:19
That sounds feasible, especially if it unlocks usage by enterprise as well.

Out of curiosity do you have links to the support you refer to? Is there an alternate URL proposed to use with the extended config?

**Comment by csMACnz** [comment] 2022-07-27 11:25
Ah, so looks like their servers actually have been having an outage incident


https://status.coveralls.io/incidents/hy0j4thbgxyz

**Comment by Giorgi** [comment] 2022-07-27 11:39
This isn't related to outages. I have been experiencing this problem for about 10 days already.

**Comment by dejan-zdravkovski-snow** [comment] 2022-07-27 13:10
I'm waiting on response from coveralls support related to static IP address that is now relevant.
The URL is the same https://coveralls.io, but it seems the current NS records are not resolving it as expected.
This seems like a trivial networking issue that should be resolved by networking infrastructure.
So, my idea was to use if needed static IP addresses for now, if the SDK supports such configuration.
@Giorgi  is right, it's happens constantly for almost 10 days, I don't think it's related to outages.

**Comment by dejan-zdravkovski-snow** [comment] 2022-07-27 13:15
Btw @csMACnz , are we sure coveralls.io did not change some requirements on the expected test results request payload?
Is there some standard / documentation that this .NET SDK for coveralls is following, should we check / reach out to ask if there are some changes in this direction?
coveralls support did not mention anything related to this, but it's a little bit unexpected to me that NS records are not being provisioned in almost 10 days, since it usually takes 24-48 hours globally.

**Comment by Giorgi** [comment] 2022-07-27 13:29
@dejan-zdravkovski-snow Are you having this problem on your local machine or on a CI system? If it's CI which one?

**Comment by dejan-zdravkovski-snow** [comment] 2022-07-27 14:41
CircleCI, cloud-based CI system.

**Comment by afinetooth** [comment] 2022-07-27 17:15
Hi, James from coveralls.io, here. Duplicating my response to this related issue here, for convenience:
https://github.com/lemurheavy/coveralls-public/issues/1654#issuecomment-1197063054

>Thanks for the report. I will share these details in the other issue.

> [...] About 10-days ago, we migrated our app to different servers. Our DNS setup should have made this change invisible to end users, which it did for most users, but some users are reporting 404 Bad Request errors.
>
> To address this we have purged cache and DNS cache at our edge service provider (Cloudflare), and we have recommended to end users that they clear any caches local to them, which could include: Browser Cache (for Web requests), Machine/OS-level cache, CI service cache, CI runner cache.
> 
> If after trying those things, users are still getting 400 Bad Request responses, in particular from the coveralls API at https://coveralls.io/api/v1, please let us know at [support@coveralls.io](mailto:support@coveralls.io).
>
> If you can provide a HAR file or verbose CI build log, that will help us investigate.

**Comment by csMACnz** [comment] 2022-07-31 04:56
Hi @dejan-zdravkovski-snow, I've had time to add that configurable `--serverUrl` argument, but ran out of time to more thoroughly test and publish.

There is a private appveyor feed (I think) that you can install from if you want to try using the pre-release build for some extra testing in the mean time.
https://ci.appveyor.com/project/MarkClearwater/coveralls-net/builds/44328288

**Comment by jympetalmd** [comment] 2022-08-02 20:23
I just ran some nslookup tests and the problem is not there:
From the machine (VM created by Jenkins for the build):
```
16:14:58  Name:      coveralls.io
16:14:58  Address 1: 172.67.72.111
16:14:58  Address 2: 104.26.4.137
16:14:58  Address 3: 104.26.5.137
``` 
And same from my docker container
`                docker run -i --rm --entrypoint bash org/dotnet-coveralls:latest -c \
                  'export DEBIAN_FRONTEND=noninteractive && apt-get update && apt-get install dnsutils -y && nslookup coveralls.io'` 
``` 
16:15:25  Non-authoritative answer:
16:15:25  Name:	coveralls.io
16:15:25  Address: 172.67.72.111
16:15:25  Name:	coveralls.io
16:15:25  Address: 104.26.4.137
16:15:25  Name:	coveralls.io
16:15:25  Address: 104.26.5.137
```

I think it might be a problem with Cloudflare caching, but without a debug mode in this binary it would be difficult to find...
@afinetooth do you have a public IP for your server (backend) that we could test without CF ?

**Comment by Giorgi** [comment] 2022-08-02 21:14
I think I found the issue. I'll try to fix the issue and send a PR.

**Comment by afinetooth** [comment] 2022-08-03 17:25
@jympetalmd We _have_ published our current list of IP addresses in this incident on our status page:
https://status.coveralls.io/incidents/2xsxq0pn5ynx

However, going direct to an IP address won't work because our SSL cert is registered to our domain (coveralls.io). You will get a warning for Web requests and an SSL error for API requests. Apologies.

Are you still experiencing the 400 Bad Request responses now?

I ask because we migrated servers again this weekend (hopefully the final time for the foreseeable future). The list of IP addresses above matches those (final) servers and we re-purged our caches at Cloudflare.

Out of four (4) users with 400 errors I've been able to personally POST their final JSON files with cURL commands successfully, and subsequently those users were able to do the same.

If you are still having the issue, feel free send a verbose Ci build log (and/or your final JSON form file attachment that would accompany your final POST to coveralls.io/api/v1/jobs) and I will test it locally and share back the working file to see if we can eliminate other causes for the 400's.

**Comment by Giorgi** [comment] 2022-08-03 18:16
The issue isn't related to coveralls.io, the upload is failing because nginx doesn't like `boundary` header with double quotes. I created a PR that fixes the upload by this tool.

**Comment by dejan-zdravkovski-snow** [comment] 2022-08-04 07:42
Hello everyone,
@Giorgi , I can also confirm the upload now works from my local dev machine as well. Great work on finding the actual issue.
I would assume nginx component was introduced in the infrastructure after coveralls.io did initial servers migration almost one month ago @afinetooth, so that was the component actually generating the 400 Bad Request response statuses all the time.
@csMACnz , I've tested the --serverUrl added parameter, and it looks ok. But, as it was already mentioned above, related to using coveralls.io cloud service, it's not usable, because SSL handshake is failing when using static public IP address directly. Still, I think it's a relevant enhancement for the SDK itself when using coveralls.io enterprise as managed instance. 
I would suggest we move forward with both enhancements, publish a new Nuget package version, and try it out within our CI/CD platforms as well. I do expect that the issue will be completely resolved now.

**Comment by csMACnz** [comment] 2022-08-05 10:08
It is weird that Nginx still has this bug since this is the default boundary format used in .Net and has been for years. I've merged the PR, and it should generate a new appveyor feed package for testing, which I can publish to nuget once your happy it works.

**Comment by csMACnz** [comment] 2022-08-05 10:10
🤔 could swear I didn't hit close on this Issue, only the PR. Reopened waiting for that confirmation and nuget publish.

**Comment by Giorgi** [comment] 2022-08-05 12:26
Worked for me:

[Use preview build of coveralls.net](https://ci.appveyor.com/project/Giorgi/entityframework-exceptions/builds/44384178#L800)

![image](https://user-images.githubusercontent.com/580749/183076788-364c659f-2a21-42a6-be49-18770ec038ce.png)

**Comment by dejan-zdravkovski-snow** [comment] 2022-08-05 13:24
Worked for me as well using CircleCI:
![image](https://user-images.githubusercontent.com/54701031/183086492-c03d45f9-b525-4991-b965-d561d93af1c9.png)
![image](https://user-images.githubusercontent.com/54701031/183086619-1eb1f3db-de5c-4f6d-82b8-b766cdb8723b.png)

**Comment by dejan-zdravkovski-snow** [comment] 2022-08-05 13:40
@csMACnz , do you think additional testing needs to be done, or the successful testing results provided by me and @Giorgi should be sufficient to publish a regular new Nuget package containing the boundary header fix?

**Comment by csMACnz** [comment] 2022-08-07 01:15
Twice is confirmation enough for me. I'll publish a new stable package version to nuget.org soon.

**Comment by csMACnz** [comment] 2022-08-07 03:00
version 4.0.1 is now on [nuget.org](https://www.nuget.org/packages/coveralls.net/4.0.1)

**Closed by csMACnz** 2022-08-07 03:00 UTC

**Comment by Giorgi** [comment] 2022-08-07 09:07
The official NuGet build worked too.

**Comment by dejan-zdravkovski-snow** [comment] 2022-08-08 08:33
Hello, I also confirm official NuGet version 4.0.1 works.
Thanks everyone for the collaboration on overcoming this issue.

**Comment by afinetooth** [comment] 2022-08-08 18:20
Thanks for the update. Issue closed at coveralls.

**Comment by Giorgi** [comment] 2022-08-15 08:42
Wrote a blog post about this issue: [How Cloudflare Broke My Build and How I Fixed It](https://www.giorgi.dev/miscellaneous/how-cloudflare-broke-my-build-and-how-i-fixed-it/)
